baseURL = 'http://veronicadeleon.de/'
languageCode = 'en-us'
title = 'Ver칩nica De Le칩n Hern치ndez'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    disableThemeToggle = true

[params.cover]
    responsiveImages = false
    linkFullImages = true


[params.homeInfoParams]
    Content = "I'm **Ver칩nica**, a **Product Designer** based in Berlin, but I thrive on agile collaboration with remote teams. I'm passionate about crafting stunning mobile apps and websites, merging design finesse with technical savvy. Let's join forces, no matter where you are, to transform concepts into digital brilliance!"

[[params.socialIcons]]
    name = "<platform>"
    url = "<link>"

[[params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Stack"
url = "/stack/"
weight = 3

[[menu.main]]
name = "Get in touch"
url = "/contact/"
weight = 4
