baseURL = 'http://veronicadeleon.de/'
languageCode = 'en-us'
title = 'Ver칩nica De Le칩n Hern치ndez'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
    disableThemeToggle = true

[params.cover]
    responsiveImages = false
    linkFullImages = true


[params.homeInfoParams]
    Content = "I'm **Ver칩nica**, a **Product Designer** based in Berlin who enjoys collaborating with remote teams. I focus on creating visually appealing and functional mobile apps and websites, combining design skills and creativity with technical knowledge."

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Stack"
url = "/stack/"
weight = 3

[[menu.main]]
name = "Get in touch"
url = "/contact/"
weight = 4
